on:
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - dev
    paths:
      - "app/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install swift-format
        run: brew install swift-format

      - name: Check Format
        run: swift-format lint --configuration app/.swift-format --recursive .

  build:
    name: build
    runs-on: macos-latest
    needs: swift_format
    steps:
      - uses: actions/checkout@v4
          
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
        
      - name: Show Xcode
        run: |
          xcodebuild -version
          xcode-select -p

      - name: Build (iOS Simulator)
        run: |
          xcrun simctl list runtimes
          xcodebuild \
            -project app/dauphin.xcodeproj \
            -scheme "dauphin" \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -sdk iphonesimulator \
            clean build

  test:
    name: test
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode
        run: |
          xcodebuild -version
          xcode-select -p

      - name: Run unit tests (iOS Simulator)
        run: |
          xcrun simctl list devices available
          xcodebuild \
            -project app/dauphin.xcodeproj \
            -scheme "dauphin" \
            -testPlan Models \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            test
