- uses: actions/checkout@v4

- name: Build with Jekyll
  uses: actions/jekyll-build-pages@v1
  with:
    source: ./Docs
    destination: ./Docs/_site

- name: Upload artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: ./Docs/_site
